# Generated by Django 4.2.4 on 2023-10-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_weatherforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
