# Generated by Django 4.2.4 on 2023-10-30 11:54

from django.db import migrations


def get_age_group(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")

    for person in person_model.objects.all():
        if person.age <= 12:
            person.age_group = "Child"
        elif person.age <= 17:
            person.age_group = "Teen"
        else:
            person.age_group = "Adult"
        person.save()


def set_age_group_default(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    age_group_default = person_model._meta.get_field("age_group").default # No age group

    for person in person_model.objects.all():
        person.age_group = age_group_default
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(get_age_group, reverse_code=set_age_group_default)
    ]
