# Generated by Django 4.2.4 on 2023-10-30 20:25

from django.db import migrations


def set_price(apps,schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")
    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        smartphone.price = len(smartphone.brand) * 120
        smartphone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price)
    ]
