# Generated by Django 4.2.4 on 2023-10-30 20:41
import datetime

from django.db import migrations


def set_delivery_and_warranty(apps, schema_editor):
    order_model = apps.get_model("main_app", "Order")
    orders = order_model.objects.all()

    for order in orders:
        if order.status == "Pending":
            order.delivery = order.order_date + datetime.timedelta(days=3)
            order.save()
        elif order.status == "Completed":
            order.warranty = "24 months"
            order.save()
        elif order.status == "Cancelled":
            order.delete()


def set_default(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_and_warranty, reverse_code=set_default)
    ]
